### PR TITLE
Add talent project page, create new custom-header

### PR DESCRIPTION
**Pull request by davidrleonard**
This PR adds a new [/talent/](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/talent-project/talent/) page to showcase our talent initiative. 

image

It also creates a re-usable "masthead-custom" class in the default layout/nav that reorgs the top of the page a bit. Frontmatter to use this class:

```
# Don't use the default masthead
masthead: "no"
nav-global-primary: "no"

# Use the custom deep masthead
masthead-custom: deep

# Content for the custom deep masthead
overline: Government Talent Initiative
page-title: There has never been a better time to work on technology inside government.
description: Engineers, designers, product managers, data scientists, and more—put your skills to work in service to your country. Let’s bring government into the 21st century together
```

/cc @lanebecker for final review
/cc @Jaime-Alexis for content final review (content has already been approved by @danhon/content team)

### CODE REVIEW

**Comment by davidrleonard** [comment]
Updated jekit link: http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/talent-project/talent/

**Comment by Jaime-Alexis** [comment]
Couple of quick thoughts...
* Remove the text directly below "Get Involved" (it's repetitive to the descriptor language)
* Can the Google form be embedded in CfA wrapper rather than take you to a new page?

**Comment by lanebecker** [comment]
Text already removed. David can speak to his plans for the Google Forms wrapper but It sounds like its a big lift and I would prefer that not hold up making this public.

**Comment by lanebecker** [comment]
@davidrleonard, shouldn't this page go under the "initatives" section of the site? maybe redirect from /talent (or I can just do a c4a.me short link.)

**Comment by davidrleonard** [comment]
Moved to [/our-work/initiatives/talent/](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/talent-project/our-work/initiatives/talent/). Merging in.

**Pull request merged**
