### PR TITLE
Update Molly's people page and added her to team page

### PR DESCRIPTION
**Pull request by mollymcleod**
I'm on the team now!

@ZoeBlumenfeld review content/quick copy edit for me?

@davidrleonard check code.

### CODE REVIEW

**Comment by davidrleonard** [comment]
Code is good to go. Fixed some indentation and tagging.

**Comment by davidrleonard** [comment]
Just waiting on @ZoeBlumenfeld. Zoe when you're good merge away.

**Comment by Jaime-Alexis** [comment]
@mollymcleod @ZoeBlumenfeld I just made some copy edits....though @davidrleonard I may not have made them the right way...so correct me on process!

**Comment by davidrleonard** [comment]
Nope, you did it correctly @Jaime-Alexis. Thanks for weighing in. I'll merge this.

**Comment by davidrleonard** [comment]
@mollymcleod approves, letting it go.

**Pull request merged**
