### PR TITLE
Added advisor - Phil Ashlock

### PR DESCRIPTION
**Pull request by greggish**
Hi - I got this image from Phil and added it in there - http://dropbox.ashlock.us/photos/profile/philipashlock-small-square-ds.jpg - but don't know if you want to upload it and/or edit?

### CODE REVIEW

**Comment by davidrleonard** [comment]
Seems like we don't need this. Closing. Tell me if I'm wrong.

**Comment by greggish** [comment]
You mean we don't need to add Phil as an advisor?

It's not necessary, but it would be nice. Not sure I understand why not.

**Comment by davidrleonard** [comment]
Sorry, my mistake. I thought you told me this wasn't relevant, I will merge in.

**Comment by davidrleonard** [comment]
Fixed the merge conflict and closed.

**Pull request merged**
