### PR TITLE
added my bio

### PR DESCRIPTION
**Pull request by jennymt**
I'ma send you a picture too. Thanks!

### CODE REVIEW

**Comment by migurski** [comment]
Looks good; we need to add a couple of things to make this show up on the website. I’ll take care of that if someone else doesn’t get to it first.

**Comment by jennymt** [comment]
I sent the pic to @davidrleonard, btw. thanks!

**Comment by davidrleonard** [comment]
Hey Jenny, sorry this took a bit for me to get to. I make some tweaks, and after merge we'll have...

* [A people page for you!](http://codeforamerica.org/people/jenny-montoya-tansey/)
* [A card for you on the team page](http://codeforamerica.org/about/team/)

Also added in your photo and changed some formatting. FYI, if you'd like to add in your Twitter/Github profiles in the future, we can do so. Right now we're just linking to LinkedIn.

**Comment by jennymt** [comment]
@davidrleonard now that I have been hanging out a bit more on github, I would like to add it. I tried to look around and see how to do that myself, but I'm not feeling super confident. Would you add it for me or talk my through it? Danka.

**Pull request merged**
