### PR TITLE
added link to prospectus

### PR DESCRIPTION
**Pull request by mattboitan0**
Linked to Google Doc version of prospectus rather than uploading a PDF - civic tech win!

### CODE REVIEW

**Comment by mattboitan0** [comment]
@davidrleonard not sure why I can't automatically merge this.

**Comment by Jaime-Alexis** [comment]
@mattboitan0 some stuff on the site has been breaking so @davidrleonard took away automatic merge. He already added the PDF yesterday. Google docs are probably even worse than PDF...I believe @davidrleonard is also working on getting some of the content from the PDF onto the page.

**Comment by mattboitan0** [comment]
@Jaime-Alexis as long as the information is there in an easily-digestible format, that works for us. Looking forward to seeing what @davidrleonard puts together.

**Comment by migurski** [comment]
@Jaime-Alexis @davidrleonard what’s been breaking? I’d like to see us get automatic merges back; they’re an important part of ensuring that a wide range of CfA people can use the site for publishing with ease and speed.

**Comment by davidrleonard** [comment]
@migurski @Jaime-Alexis automatic merges are back, there was a Travis fail.

**Comment by davidrleonard** [comment]
Yeah so following up ... this is a merge conflict. Which is different than our deployment process. Read more about mergeconflicts here: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Pull request merged**
