### PR TITLE
Refreshed the /geeks page

### PR DESCRIPTION
**Pull request by ondrae**
Hey @Jaime-Alexis and @mollymcleod 

I've started to redo the /geeks page and it could use some love. http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/geeks-refresh/geeks/

Have any suggestions? I really miss the Geek of the Week from the [live version](http://codeforamerica.org/geeks).

### CODE REVIEW

**Comment by Jaime-Alexis** [comment]
Hm, yes, happy to help! I think @davidrleonard could provide some insights as well. 

Couple of things:
* would suggest 'citizens have power" vs. "geeks" because some people may not identify has geeks
* the three sections for time need to be better differentiated and need a little text love. Maybe @ZoeBlumenfeld can help with that after she gets back from NTC.
* for the Geek of the Week, didn't you say it didn't get much traffic? I'd be ok with leaving it, but if it's not getting clicked, probably not useful.

**Comment by ondrae** [comment]
Okay tried a different layout. http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/geeks-refresh/geeks/

It has three horizontal sections, instead of columns. They are labelled about how much time you have to get involved. 
* Have an hour?
* Have one night a week?
* Want a year long opportunity?
* Want to change careers?

**Comment by ondrae** [comment]
18f used the same breakdown by time. 
image

**Comment by ondrae** [comment]
@mollymcleod and @ZoeBlumenfeld suggested:
* Change "Code for America Right Now" to "You can code for America right now."
* Instead of map, change to a picture with a link to the Brigade site. With text overlay.
* Try out having some blog posts on the bottom ...
* "You have the power to help your city."

**Comment by Jaime-Alexis** [comment]
And also, maybe instead of 'want a career change' try 'want to work on
things that matter?'

Looking good!

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by davidrleonard** [comment]
This is looking solid, @ondrae are you still working or is this waiting on more feedback?

**Pull request merged**
